### PR TITLE
Randomize the chars for every transaction

### PR DESCRIPTION
**Pull request by chalchuck**
I was going through your code and the thought of randomizing the chars for every transaction hit me, it makes sense to me because it will at all times ensure a new string of chars is generated for every transaction therefore reducing to a higher level chances of duplicate nonces.

### CODE REVIEW

**Comment by itsmrwave** [comment]
@chalchuck Noticed your fork ... but you made the pull request to yourself (unless that was the intention - the description suggests otherwise). I must admit, the nonce generation could use some improvement (and flexibility). By flexibility, allow the user to specify this themselves.

cc:/ @mogetutu

**Comment by chalchuck** [comment]
It wasn't my intention to fork it to myself, I just clicked the fork button
and I made the changes and saved them.
How's supposed to be done?

**Comment by itsmrwave** [comment]
@chalchuck No. You forked alright ... but you made a pull request to your own repo. Find a good guide to this process here ... https://help.github.com/articles/using-pull-requests/.

Anyway ... if you would like me to rethink some aspects of the gem you could also [create an issue][1] ... so that I can factor in your ideas in the next release.

[1]: https://github.com/itsmrwave/pesapal-gem/issues/new

**Comment by chalchuck** [comment]
Thank I'll do that, soon.

**Pull request closed without merging**
